version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - '3333:3333'
    environment:
      - HOST=0.0.0.0
      - PORT=3333
      - NODE_ENV=production
      - DB_CONNECTION=mysql
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB_NAME=24_game_db
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: 24_game_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
